"""Build the reproducible four-model SDN DDoS training notebook."""
from pathlib import Path
import nbformat as nbf

OUT = Path(__file__).resolve().parent / "04_ml_model_training.ipynb"
cells = [
    ("md", "# SDN DDoS model training and evaluation\n\nThis notebook trains Decision Tree, Random Forest, K-Nearest Neighbors, and Logistic Regression on controlled synthetic SDN telemetry. It reports held-out accuracy, macro precision, macro recall, macro F1, and per-record prediction latency.\n\n**Scope note:** the dataset is synthetic lab telemetry, not a packet capture or evidence of live-network performance. Identifiers, labels, attack-family metadata, attack intensity, and attacker count are excluded from features to prevent obvious label leakage."),
    ("code", "from pathlib import Path\nfrom time import perf_counter\nimport json\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.impute import SimpleImputer\nfrom sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.preprocessing import OneHotEncoder, StandardScaler\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.neighbors import KNeighborsClassifier\nfrom sklearn.linear_model import LogisticRegression\n\nROOT = Path.cwd().resolve()\nif not (ROOT / 'data').exists(): ROOT = ROOT.parent\nDATASET = ROOT / 'data/processed/sdn_ddos_versatile.parquet'\nRESULTS = ROOT / 'analytics/results'; RESULTS.mkdir(parents=True, exist_ok=True)\nRANDOM_STATE = 42\nprint(f'Dataset: {DATASET}')\nprint(f'Plot directory: {RESULTS}')"),
    ("code", "df = pd.read_parquet(DATASET)\nmetadata = json.loads(DATASET.with_suffix('.json').read_text())\nprint(f\"Rows: {len(df):,} | Columns: {len(df.columns)} | Classes: {df['label'].nunique()}\")\nprint(metadata['limitations'])\ndisplay(df.head(3))\ndisplay(df['label'].value_counts().sort_index().rename('records').to_frame())\n\nplt.figure(figsize=(12, 4))\ndf['label'].value_counts().sort_index().plot.bar(color='#3572A5')\nplt.title('Balanced controlled SDN telemetry by class'); plt.ylabel('Windows'); plt.xticks(rotation=35, ha='right'); plt.tight_layout()\nplt.savefig(RESULTS / 'class_distribution.png', dpi=160); plt.show()"),
    ("md", "## Prepare an honest feature matrix\n\nCategorical telemetry context is one-hot encoded. Numeric telemetry is median-imputed and standardized; this supports KNN and logistic regression. The split is stratified into 70% train, 15% validation, and 15% test. The validation partition is retained for later tuning; metrics below use only the held-out test set."),
    ("code", "leakage_or_id = {'timestamp_utc', 'experiment_id', 'window_id', 'window_sequence', 'src_host', 'dst_host', 'label', 'attack_family', 'data_source', 'schema_version', 'attack_intensity', 'attacker_count'}\nfeature_columns = [c for c in df.columns if c not in leakage_or_id]\ncategorical = df[feature_columns].select_dtypes(include=['object', 'category']).columns.tolist()\nnumeric = [c for c in feature_columns if c not in categorical]\nX, y = df[feature_columns], df['label']\nX_train, X_holdout, y_train, y_holdout = train_test_split(X, y, test_size=.30, random_state=RANDOM_STATE, stratify=y)\nX_valid, X_test, y_valid, y_test = train_test_split(X_holdout, y_holdout, test_size=.50, random_state=RANDOM_STATE, stratify=y_holdout)\nprint(f'Features: {len(feature_columns)} ({len(numeric)} numeric, {len(categorical)} categorical)')\nprint(f'Train/validation/test: {len(X_train):,} / {len(X_valid):,} / {len(X_test):,}')\nassert not set(leakage_or_id - {'label'}).intersection(feature_columns)\npreprocessor = ColumnTransformer([('numeric', Pipeline([('imputer', SimpleImputer(strategy='median')), ('scale', StandardScaler())]), numeric), ('categorical', Pipeline([('imputer', SimpleImputer(strategy='most_frequent')), ('onehot', OneHotEncoder(handle_unknown='ignore'))]), categorical)])"),
    ("md", "## Train four lightweight baselines\n\nThe models reflect the literature survey’s practical ML baseline: interpretable tree, ensemble tree, distance-based classifier, and linear classifier. This is intentionally not a deep-learning benchmark."),
    ("code", "models = {'Decision Tree': DecisionTreeClassifier(max_depth=16, min_samples_leaf=3, class_weight='balanced', random_state=RANDOM_STATE), 'Random Forest': RandomForestClassifier(n_estimators=150, min_samples_leaf=2, class_weight='balanced_subsample', n_jobs=-1, random_state=RANDOM_STATE), 'KNN': KNeighborsClassifier(n_neighbors=11, weights='distance', n_jobs=-1), 'Logistic Regression': LogisticRegression(C=2.0, max_iter=1200, class_weight='balanced', n_jobs=-1, random_state=RANDOM_STATE)}\nfitted, rows = {}, []\nfor name, model in models.items():\n    pipeline = Pipeline([('preprocess', preprocessor), ('model', model)])\n    fit_start = perf_counter(); pipeline.fit(X_train, y_train); fit_seconds = perf_counter() - fit_start\n    pred_start = perf_counter(); pred = pipeline.predict(X_test); predict_seconds = perf_counter() - pred_start\n    precision, recall, f1, _ = precision_recall_fscore_support(y_test, pred, average='macro', zero_division=0)\n    rows.append({'model': name, 'accuracy': accuracy_score(y_test, pred), 'precision_macro': precision, 'recall_macro': recall, 'f1_macro': f1, 'fit_seconds': fit_seconds, 'prediction_ms_per_record': 1000 * predict_seconds / len(X_test)})\n    fitted[name] = (pipeline, pred)\nresults = pd.DataFrame(rows).sort_values(['f1_macro', 'accuracy'], ascending=False).reset_index(drop=True)\ndisplay(results.round(4))\nresults.to_csv(RESULTS / 'model_metrics.csv', index=False)"),
    ("code", "metric_plot = results.melt(id_vars='model', value_vars=['accuracy', 'precision_macro', 'recall_macro', 'f1_macro'], var_name='metric', value_name='score')\nplt.figure(figsize=(11, 5)); sns.barplot(metric_plot, x='model', y='score', hue='metric', palette='deep')\nplt.ylim(0, 1.05); plt.title('Held-out test performance by model'); plt.ylabel('Macro score / accuracy'); plt.xlabel(''); plt.legend(title=''); plt.tight_layout()\nplt.savefig(RESULTS / 'model_comparison.png', dpi=160); plt.show()\nplt.figure(figsize=(8, 4)); sns.barplot(results, x='model', y='prediction_ms_per_record', color='#D65F5F')\nplt.title('Held-out inference latency'); plt.ylabel('Milliseconds per record'); plt.xlabel(''); plt.tight_layout()\nplt.savefig(RESULTS / 'inference_latency.png', dpi=160); plt.show()"),
    ("md", "## Error analysis and feature relevance\n\nThe confusion matrix uses the best macro-F1 model. Random Forest feature importance is shown separately because it provides a useful global ranking; it is descriptive rather than causal."),
    ("code", "best_name = results.loc[0, 'model']; best_pipeline, best_pred = fitted[best_name]\nlabels = sorted(y_test.unique()); cm = confusion_matrix(y_test, best_pred, labels=labels, normalize='true')\nplt.figure(figsize=(12, 10)); sns.heatmap(cm, cmap='Blues', vmin=0, vmax=1, xticklabels=labels, yticklabels=labels, square=True)\nplt.title(f'Normalized confusion matrix — {best_name}'); plt.xlabel('Predicted'); plt.ylabel('Actual'); plt.xticks(rotation=45, ha='right'); plt.tight_layout()\nplt.savefig(RESULTS / 'best_model_confusion_matrix.png', dpi=180); plt.show()\nrf = fitted['Random Forest'][0]; feature_names = rf.named_steps['preprocess'].get_feature_names_out()\nimportance = pd.Series(rf.named_steps['model'].feature_importances_, index=feature_names).sort_values(ascending=False).head(18).sort_values()\nplt.figure(figsize=(9, 7)); importance.plot.barh(color='#55A868'); plt.title('Random Forest top 18 feature importances'); plt.xlabel('Impurity-based importance'); plt.tight_layout()\nplt.savefig(RESULTS / 'random_forest_feature_importance.png', dpi=160); plt.show()\nprint(f\"Best held-out macro-F1: {best_name} ({results.loc[0, 'f1_macro']:.4f})\")"),
    ("md", "## Conclusion\n\nThe notebook saves plots and `model_metrics.csv` to `analytics/results`. Before deployment claims, validate against separate real OpenFlow/Ryu telemetry and benchmark data, then measure the full Kafka → Spark → model → Ryu response latency."),
]
nb = nbf.v4.new_notebook(cells=[nbf.v4.new_markdown_cell(s) if k == "md" else nbf.v4.new_code_cell(s) for k, s in cells])
nb.metadata = {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}, "language_info": {"name": "python", "version": "3.12"}}
nbf.write(nb, OUT)
print(OUT)
